# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 14:49
from __future__ import unicode_literals

import black.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(max_length=200, upload_to=black.models.upload_location),
        ),
    ]
