# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 17:39
from __future__ import unicode_literals

import black.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black', '0008_auto_20160817_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(height_field='height_field', upload_to=black.models.upload_location, width_field='width_field'),
        ),
    ]
