# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 17:47
from __future__ import unicode_literals

import black.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black', '0009_auto_20160817_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=black.models.upload_location),
        ),
    ]
