# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 17:59
from __future__ import unicode_literals

import black.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black', '0010_auto_20160817_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(default=None, upload_to=black.models.upload_location),
        ),
    ]
