# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 18:00
from __future__ import unicode_literals

import black.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black', '0011_auto_20160817_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1, upload_to=black.models.upload_location),
            preserve_default=False,
        ),
    ]
